export enum UserRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  TECHNICIAN = 'TECHNICIAN',
  VIEWER = 'VIEWER',
}

export enum RepairStatus {
  RECEIVED = 'RECEIVED',
  INSPECTION = 'INSPECTION',
  DIAGNOSIS = 'DIAGNOSIS',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  REPAIRING = 'REPAIRING',
  TESTING = 'TESTING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  UNREPAIRABLE = 'UNREPAIRABLE',
  RETURNED = 'RETURNED',
}

export enum SymptomCategory {
  POWER = 'POWER',
  DISPLAY = 'DISPLAY',
  CHARGING = 'CHARGING',
  AUDIO = 'AUDIO',
  CONNECTIVITY = 'CONNECTIVITY',
  THERMAL = 'THERMAL',
  PERFORMANCE = 'PERFORMANCE',
  PHYSICAL_DAMAGE = 'PHYSICAL_DAMAGE',
  SENSORS = 'SENSORS',
  OTHER = 'OTHER',
}

export enum ComponentCategory {
  PMIC = 'PMIC',
  MOSFET = 'MOSFET',
  BUCK_CONTROLLER = 'BUCK_CONTROLLER',
  LDO = 'LDO',
  CAPACITOR = 'CAPACITOR',
  RESISTOR = 'RESISTOR',
  DIODE = 'DIODE',
  INDUCTOR = 'INDUCTOR',
  USB_PD_CONTROLLER = 'USB_PD_CONTROLLER',
  CHARGING_IC = 'CHARGING_IC',
  AUDIO_CODEC = 'AUDIO_CODEC',
  EMBEDDED_CONTROLLER = 'EMBEDDED_CONTROLLER',
  CONNECTOR = 'CONNECTOR',
  CRYSTAL_OSCILLATOR = 'CRYSTAL_OSCILLATOR',
  LOGIC_GATE = 'LOGIC_GATE',
  DISPLAY_PANEL = 'DISPLAY_PANEL',
  BATTERY = 'BATTERY',
  KEYBOARD = 'KEYBOARD',
  OTHER = 'OTHER',
}

export enum RepairActionType {
  REPLACED = 'REPLACED',
  REPAIRED = 'REPAIRED',
  REFLOWED = 'REFLOWED',
  REBALLED = 'REBALLED',
  CLEANED = 'CLEANED',
  RESEATED = 'RESEATED',
  REPROGRAMMED = 'REPROGRAMMED',
  UPDATED = 'UPDATED',
  ADJUSTED = 'ADJUSTED',
  NO_ACTION = 'NO_ACTION',
}

export enum TestOutcome {
  SUCCESSFUL = 'SUCCESSFUL',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  UNREPAIRABLE = 'UNREPAIRABLE',
  UNKNOWN = 'UNKNOWN',
}

export enum EvidenceConfidence {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}
